Fix context overflow issue causing commit submission failure
devchat-ai/workflows pull request #49
Opened 2024-01-23 05:18 UTC by yangbobo2021

This pull request addresses the context overflow error that was causing the second commit submission to fail when generating Chinese commit messages.

Changes made:
- Set the language code to "en" in `commit/command.yml`.
- Modified `commit/commit.py` to handle errors related to the model's maximum context length.
- Updated `commit/zh/command.yml` with "zh" language code.
- Adjusted `libs/llm_api/openai.py` to bypass the token limit error.

By merging this pull request, we should see the issue resolved and both English and Chinese commit submissions working as expected.

Closes devchat-ai/devchat#189

2024-01-24 03:44 UTC, kagami-l requested changes

2024-01-24 03:44 UTC, kagami-l commented on commit/commit.py
> +    language_prompt = "You must response commit message in chinese。\n" if language == "zh" else ""
多语言支持应参考 unit_tests/i18n.py 使用`gettext`模块相对规范地实现，而非三元表达式 （后面类似地方不再赘述）

2024-01-24 03:44 UTC, kagami-l commented on commit/commit.py
> +    if len(str(prompt)) > 20000:
1. 使用常量而非hard coding
2. 最好用tiktoken计算token size，而非间接限制字符串长度，字符串长度与token size表现不一定一致
3. 必要的话应该为不同模型配置不同的size限制

2024-01-24 03:44 UTC, kagami-l commented on libs/llm_api/openai.py
> +                print("Exception3:", err, file=sys.stderr, flush=True)
无意义的 Exception3、Exception2，应输出有意义、有帮助的相关信息

2024-01-24 03:48 UTC, kagami-l commented on commit/commit.py
> +    language_prompt = "You must response commit message in chinese。\n" if language == "zh" else ""
另外/commit 中其他提示没有多语言，仅这个pr的部分支持中英，使用感觉不协调

2024-01-24 08:26 UTC, kagami-l commented on libs/llm_api/openai.py
> +                return {"content": err.message, "function_name": None, "parameters": ""}
这不是一种好的处理超限的方式，尤其是将openai.py定义为公用的llm请求模块（虽然只在/commit里使用），过分干涉返回结果，要求使用方必须针对返回内容作不同业务处理（也是目前已有代码的缺陷）。
一种根据现状的轻量修改是定义超限的异常类型后raise，业务处理只需catch相应错误

2024-01-24 09:35 UTC, yangbobo2021 commented on libs/llm_api/openai.py
> +                print("Exception3:", err, file=sys.stderr, flush=True)
这里2，3是当时用于测试验证，不是需要需要的信息。

2024-01-24 09:59 UTC, yangbobo2021 commented on commit/commit.py
> +    if len(str(prompt)) > 20000:
使用常量而非hard coding. 同意。
2，3，暂时先不修改，优先级较低，后续专门安排一个ISSUE来设计处理。

2024-01-25 09:50 UTC, kagami-l approved these changes

2024-01-25 09:50 UTC, merged