Add group UI wrapper
devchat-ai/workflows pull request #8
Opened 2023-12-14 03:12 UTC by yangbobo2021

2023-12-14 07:08 UTC, kagami-l requested changes

2023-12-14 07:08 UTC, kagami-l commented on libs/ui_utils/group.py
> +    )
Do not overuse list comprehension. it's less readable.
just use `for` and `if-elif`:

```python
res = []
for m in ui_message:
   ele = None
   
   if m[0] == "editor":
      ele = editor_answer(response, m[2])
   elif ...:
      ...
   elif ...:
      ...

   res.append(ele)
```

2023-12-18 12:03 UTC, kagami-l commented on libs/ui_utils/__init__.py
> +    "ui_group",
新增暴露`make_*_control`系列接口 跟前面的 `ui_*`的区别是什么？像`commit.py`里仍用的`ui_*`系列，新暴露的函数并没有在外使用，那么他们应该什么时候被用到？

2023-12-18 12:37 UTC, yangbobo2021 commented on libs/ui_utils/__init__.py
> +    "ui_group",
大概是这样使用：
(check_result, edit_result) = ui_group(
    make_check_control(...),
    make_editor_control(...)
)
make_checkbox_control用于生成复合UI规范的描述字符串。

2023-12-18 13:05 UTC, kagami-l approved these changes

2023-12-18 13:11 UTC, merged